### ISSUE TITLE
angular-graphql-master.zip on the onboarding tutorial does not include .angular-cli.json

### ISSUE THREAD

**Issue by JPinlac** [graphcool-examples/angular-graphql#3]

**Comment by schickling** [comment]
Fixed. Could you please try again?

**Comment by JPinlac** [comment]
Thanks, I'm not sure how to get back to that onboarding tutorial to find the download link. So, I won't be able check myself.

**Comment by marktani** [comment]
I just checked it and it should be fine. Thanks for the heads up, @JPinlac 🙏
